[IV-22-23] Objetivo 3
martahuetem/IV_HorseMatch pull request #20
Opened 2022-11-17 10:29 UTC by martahuetem

2022-11-17 10:54 UTC, martahuetem commented
@JJ listo para revisión

2022-11-17 12:52 UTC, JJ commented on docs/gestor_dependencias.md
> +Los gestores de dependencias más utilizados para node.js son:
No te pido los más utilizados, sino que pongas los criterios de antemano. Por favor, lee errores frecuentes y la presentación sobre criterios doe elección.

2022-11-17 12:52 UTC, JJ commented on docs/gestor_dependencias.md
> +Es un gestor de paquetes creado en lenguaje JAvaScript y es la parte esencial de Node.js.
typo

2022-11-17 12:53 UTC, JJ commented on docs/gestor_dependencias.md
> +2. Tiene la mayor selección de paquetes.
Los gestores de paquetes no tienen "selección" de paquetes. Diferencia el CLI del repositorio en el que trabaja.

2022-11-17 12:53 UTC, JJ commented on docs/gestor_dependencias.md
> +3. Se tiene bastantante información sobre él.
No es un criterio objetivo.

2022-11-17 12:54 UTC, JJ commented on docs/gestor_dependencias.md
> +4. Se obtiene cualquier librería a través de una única linea de código, la cual que permite integrar dependencias, distribuir paquetes y administrar módulos.
Por favor, poned las cosas que los diferencien, no en lo que coinciden. Y sólo en lo relativo a los criterios de elección

2022-11-17 12:54 UTC, JJ commented on docs/gestor_dependencias.md
> +1. Se tienen problemas de permisos si se hace uso de *sudo*
Es que no se debe usar nunca sudo.

2022-11-17 12:54 UTC, JJ commented on docs/gestor_dependencias.md
> +2. Ha tenido algunos problemas de seguridad a lo largo de sus 10 años. Sin embargo, se han ido solucionando.
npm  no ha tenido ningún problema. Quizás el repo.

2022-11-17 12:56 UTC, JJ commented on docs/gestor_dependencias.md
> +1. Tiene soporte para monorepo.
¿Es un requisito?

2022-11-20 10:36 UTC, martahuetem commented
@JJ solicito revisión.

2022-11-21 08:10 UTC, JJ commented on docs/gestor_dependencias.md
> +1. Tiene soporte para monorepo.
No resolváis lo no habéis resuelto.

2022-11-21 10:29 UTC, martahuetem commented
Ahora si. Perdón, pensaba que lo había eliminado y por eso lo resolví. 
@JJ solicito revisión.

2022-11-21 10:37 UTC, JJ requested changes
Perdón, por alguna razón se me había olvidado poner esto.

2022-11-24 08:53 UTC, martahuetem commented
@JJ solicito revisión.

2022-11-24 10:59 UTC, JJ commented
Las buenas prácticas en los mensajes de commit tienes que seguirlas en todos los objetivos.

2022-11-24 11:04 UTC, JJ commented
[`yarn` tiene 85 de puntuación](https://snyk.io/advisor/search?source=npm&q=yarn). Tampoco creo que sea como para echarse las manos a la cabeza.

2022-11-24 16:27 UTC, JJ approved these changes
👍 Puedes cambiar lo dicho antes del siguiente, y por favor no cierres mis comentarios sin hacer nada al respecto.

2022-11-24 16:27 UTC, JJ commented on docs/gestor_dependencias.md
> +1. No soporta, en un principio, los lock files de npm. Sin embargo, hay un comando que convierte los lock files de npm o yarn a pnpm.
¿Por qué tendría que hacerlo?

2022-11-24 16:27 UTC, JJ commented on docs/gestor_dependencias.md
> +1. **Freshness:** En este caso tanto npm como yarn y pnpm se actualizan continuamente.
Tendrías que definir "continuamente". `yarn` lleva 6 meses sin actualizarse.

2022-11-24 16:27 UTC, JJ commented on src/caballo.js
> +
... no meter ruido es quitarlo de este PR y ponerlo en otro, no cerrarme mi comentario sin hacer nada al respecto.

2022-12-01 08:04 UTC, merged