Objetivo 1
martahuetem/IV_HorseMatch pull request #6
Opened 2022-10-14 06:55 UTC by martahuetem

2022-10-14 07:33 UTC, martahuetem commented
**MILESTONES**
* [x] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [x] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [x] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [x] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [x] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [x] ¿Todos los milestones describen correctamente un producto, y no un
   concepto vago, una funcionalidad o una tarea?
* [x] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [x] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [x]  ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [x]  ¿El milestone 0 es mínimo *y* viable?
* [ ]  ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [x] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?
HISTORIAS DE USUARIO
* [x] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [x] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
* [x] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
* [x] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2022-10-15 09:01 UTC, iscoct requested changes

2022-10-15 09:01 UTC, iscoct commented on docs/personas.md
> +Alumno del centro hípico. <br />
Aunque está bien ponerse en el punto de vista del usuario, no veo ninguna referencia de cómo estos usuarios interaccionarán con el sistema.

Es decir, si yo soy alumno, ¿voy a una aplicación web o móvil para reservar un caballo y me asignan uno antes de ir?, ¿lo puede hacer con antelación días antes o justo antes de ir?

Si hace la reserva hace unos días, ¿debería confirmar cuando quede poco tiempo para su entreno?

Me refiero a que falta el flujo de cómo los usuarios usan o las personas del centro administran el sistema.

Concretar un poco el flujo y cómo las personas utilizan ese software.

2022-10-17 11:34 UTC, JJ commented
Pon los milestones en el cuerpo del PR, por favor.

2022-10-17 11:34 UTC, JJ commented on docs/milestones.md
> +[M3] Diseño de la interfaz
No, no se va a implementar.

2022-10-17 15:38 UTC, martahuetem commented on docs/milestones.md
> +[M3] Diseño de la interfaz
@iscoct acabo de modificarlo. No se si así estará correcto. Muchas gracias

2022-10-19 10:45 UTC, JJ commented on docs/personas.md
> +Alumno del centro hípico. <br />
No es muy relevante para la asignatura, pero no está mal.

2022-10-19 10:48 UTC, JJ approved these changes
Está todo lo que tiene que estar, aunque algunos cambios de detalle vendrían bien antes del siguiente ciclo. En especial, M1 es o innecesario o está fuera de secuencia.

2022-10-19 10:48 UTC, JJ commented on docs/historias.md
> +Pablo que va todos los miercoles, día en el que hay más afluencia) no quiere quedarse sin caballo.
typo

2022-10-19 10:48 UTC, JJ commented on docs/milestones.md
> +[M0] Fichero con el modelo de datos
O ficheros

2022-10-19 10:48 UTC, JJ commented on docs/milestones.md
> +[M1] Librerías necesarias para obtener la información de los caballos
Solo hay una librería (y no se dice librería, sino biblioteca), que es la que incluye el proyecto.

2022-10-19 10:48 UTC, JJ commented on docs/milestones.md
> +Diseño de una librería para obtener la información de la estructura de datos detallada en [M0] y que nos permita la modificación, inserción... de los datos necesarios a dicha estructura de datos.
El ciclo CRUD no tiene nada que ver con la lógica de negocio. Y sólo es necesario cuando es necesario, de acuerdo con las HU.

2022-10-19 11:07 UTC, merged

2022-10-19 11:15 UTC, iscoct commented on docs/milestones.md
> +[M3] Diseño de la interfaz
Sí, el cambio a ido a mejor.